# Generated by Django 4.2.9 on 2024-02-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0032_invoice_alter_companytype_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='price_in_dinar',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_in_dollar',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.JSONField(),
        ),
    ]
