# Generated by Django 4.2.9 on 2024-02-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0033_remove_invoice_price_in_dinar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='123123', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
