# Generated by Django 4.2.9 on 2024-02-25 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0034_invoice_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
